build_shop/User/urls.py
from django.urls import path,include
from .import views
app_name="user"
urlpatterns = [
    path('addDelivery/',views.CreateDelivery.as_view(),name="add_delivery"),
]

build_shop/build_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('user/',include('User.urls')),
    path('management/',include('management_owner.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

build_shop/cart/urls.py
from django.urls import path
from .import views

app_name='cart'
urlpatterns = [
    path('',views.DetailCart.as_view(), name="detail_cart"),
    path('delete/<str:product_id>/',views.deleteProductCart,name="delete_product_cart"),
    path('product_detail/<slug:slug>/',views.AddProductCart.as_view(),name='add_product_cart'),
    path('post_comment/>',views.post_Comment,name='post_comment'),
    path('test/',views.test.as_view()),
]

build_shop/home/urls.py
from django.urls import path,include
from .import views
from django.contrib.auth.decorators import login_required
app_name='home'
urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('login-register/',views.SiteLoginRegister.as_view(),name='login-register'),
    path('logout/',views.logout_function,name="logout"),  
    path('cc/',views.regis.as_view(),name="cc"),
    # path("dashboard/",views.dashboard,name="dashboard"),
    #  path("dashboard/",views.vdashboard.as_view(),name="dashboard"),
]

build_shop/management_owner/urls.py
from django.urls import path,include
from .import views
app_name="management"
urlpatterns = [
    path('',views.index),
    path('1/',views.id),
    path('dashboard/',views.Dashboard.as_view(),name='dashboard'),
]

build_shop/home/models.py
from django.db import models

# Create your models here.

build_shop/home/forms.py
from django import forms
from django.core.exceptions import ValidationError


    
class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(),required=True)
    password = forms.CharField(widget=forms.PasswordInput(),required=True)
    is_admin=forms.BooleanField(required=False)
    
    def __init__(self,*arg,**kwargs):
        super().__init__(*arg,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({ 'class':'input'})
    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if len(username) >10:
            self.add_error('username','nho hon 5')
        if len(password)>5:
            self.add_error('password','nho hon 5')
            self.add_error('password','nho hon 4')
            
        return self.cleaned_data 
class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'id':1,'placeholder':'Username'}),required=True)
    password_1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password_1'}),required=True)
    password_2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password_2'}),required=True)
        
        
    def __init__(self,*arg,**kwargs):
        super().__init__(*arg,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({ 'class':'input'})
            
    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        password_1 = self.cleaned_data.get('password_1')
        password_2 = self.cleaned_data.get('password_2')
        if password_1!=password_2:
            self.add_error('password_2','Two password are not same!')
        
        return self.cleaned_data
        

build_shop/home/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render,HttpResponse
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login,logout
from .forms import *
from pprint import  pprint
from django.db.models import Q
from shop.models import Category,Product
import json
from django.contrib.auth.decorators import login_required
# Create your views here.
class Home(LoginRequiredMixin,TemplateView):
    template_name="home/index.html"
    login_url='home:login-register'
    
    def get(self, request):
        request.session['color']='reds'
        print(request.session['color'])
        categories=Category.objects.all()
        products=Product.objects.all()
        return super().get(request,products=products,categories=categories)    
    
    def post(self,request):
        cate_filter=[];price_filter=[]
        for i in request.POST:
            try:
                index=int(i.index('-'))
                flag=i[0:index]
                name_filter=i[index+1:]
                if flag=='cate':
                    cate_filter.append(name_filter)
                if flag=='price':
                    price_filter.append( request.POST.get(i))
            except:
                pass

        products=Product.objects.filter(Q(Category__Name__in=cate_filter))
        products=products.filter(Q(price__gte=float(price_filter[0])),Q(price__lte=float(price_filter[1])) )
        categories = Category.objects.all()
        return render(request,
                    'home/index.html',{
                    'categories': categories,
                    'products': products})
        
        
class SiteLoginRegister(TemplateView):    
    template_name='home/login-register.html'
    login_form=LoginForm()
    register_form=RegisterForm()
    
    def get(self,request):
        return super().get(request)
    
    def post(self,request):
        
        # login form..
        if request.POST.get('form-type')=='login_form' and request.is_ajax() :
            login_form=LoginForm(request.POST)
            valid=False;flag=False;is_admin=False
            tmp={}
            if login_form.is_valid():
                cd=login_form.cleaned_data
                message_error=[]
                user = authenticate(username=cd['username']
                                    ,password=cd['password'])
                is_admin=cd['is_admin']
                if user is not None:
                    login(request,user=user)
                    valid=True 
                    request.session.set_expiry(0)
                else:
                    flag=True
            error_dict=dict(login_form.errors.items())
            if flag==True:
                error_dict['mess_account']=["Account is not correct!"]
            error_dict=json.dumps(error_dict)
            return JsonResponse({'valid':valid,
                                 'is_admin':is_admin,
                                 'error_dict':error_dict}
                                )
        return HttpResponse("Fail")    
               
                
                #      return self.render_to_response(
                #          self.get_context_data(message="loi nha!")
                #         )   
                       
        
        # register form..    
        if request.POST.get('form-type')=='register_form':
            register_form=RegisterForm(request.POST)
            if register_form.is_valid():
                return HttpResponse("C")
            else:
                return self.render_to_response(self.get_context_data(register_form=register_form))
            
    def get_context_data(self,login_form=None,register_form=None,**kwargs):
        context=super().get_context_data() 
        for key,value in kwargs.items():
            context[key]=value
        if login_form is  None:
            login_form=self.login_form
        if register_form is  None:
            register_form=self.register_form
            
        context['login_form']=login_form    
        context['register_form']=register_form
        return context
                
       


def logout_function(request):
    logout(request)
    return redirect('home:login-register')


class regis(FormView):
    form_class=LoginForm
    template_name='cc.html'
    
    def form_valid(self, form):
        cd=form.cleaned_data
        message_error=[]
        user = authenticate(username=cd['username']
                            ,password=cd['password'])
        if user is not None:
            pass
            login(self.request,user=user)
            return redirect("management:dashboard")
        
    def form_invalid(self, form):
        
        return super().form_invalid(form)
    

def check_odecoratorwner(user):
    return user.is_owner


# @user_passes_test(check_owner,login_url="home:cc")


# @only_admin(context="acess denied")
# @user_passes_test(check_owner,login_url="home:cc")
# def dashboard(request):   
#     return HttpResponse("dashboard")

# from django.contrib.auth.mixins import UserPassesTestMixin

# class vdashboard(UserPassesTestMixin,TemplateView):
#     login_url="home:cc"
    
#     def test_func(self):
#         return True
    
#     def get(self,request):
#         return HttpResponse("dashboard!")    


    
    
        
        
        
        
    
        

build_shop/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %} 
        {% endblock head %}
        {% block title %}
  
        {% endblock title %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <link rel="shortcut icon" type="image/icon" href="/media/assets/logo/favicon.png"/>
		 
		  <!--font-awesome.min.css-->
		  <link rel="stylesheet" href="/media/assets/css/font-awesome.min.css">
  
		  <!--linear icon css-->
		  <link rel="stylesheet" href="/media/assets/css/linearicons.css">
  
		  <!--animate.css-->
		  <link rel="stylesheet" href="/media/assets/css/animate.css">
  
		  <!--owl.carousel.css-->
		  <link rel="stylesheet" href="/media/assets/css/owl.carousel.min.css">
		  <link rel="stylesheet" href="/media/assets/css/owl.theme.default.min.css">
		  
		  <!--bootstrap.min.css-->
		  <link rel="stylesheet" href="/media/assets/css/bootstrap.min.css">
		  
		  <!-- bootsnav -->
		  <link rel="stylesheet" href="/media/assets/css/bootsnav.css" >	
		  
		  <!--style.css-->
		  <link rel="stylesheet" href="/media/assets/css/style.css">
		  
		  <!--responsive.css-->
		  <link rel="stylesheet" href="/media/assets/css/responsive.css">
        <!--font-family-->
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {% block link %}
        {% endblock link %}
        {% block style %}
            <style>
                .cart{
                    height: 50px;
                    background-color:red;
                }
                
            </style>
        {% endblock style %}
    </head>
    <body>
        <header id="home" class="welcome-hero">
            <div class="top-area">
                <div class="header-area">
                    <!-- Start Navigation -->
                    <nav class="navbar navbar-default bootsnav  navbar-sticky navbar-scrollspy"  data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">
                        <!-- Start Top Search -->
                        <div class="top-search">
                            <div class="container">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                    <input type="text" class="form-control" placeholder="Search">
                                    <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
                                </div>
                            </div>
                        </div>
                        <!-- End Top Search -->
    
                        <div class="container">            
                            <!-- Start Atribute Navigation -->
                            <div class="attr-nav">
                                <ul>
                                    <li class="search">
                                        <a href="#"><span class="lnr lnr-magnifier"></span></a>
                                    </li><!--/.search-->
                                    <li class="nav-setting">
                                        <a href="#"><span class="lnr lnr-cog"></span></a>
                                    </li><!--/.search-->
                                    <li class="nav-cart">
                                        <a href="{% url 'cart:detail_cart' %}">
                                            <span class="lnr lnr-cart"></span>
                                            <span class="badge badge-bg-1">
                                                    {{cart|length}}
                                            </span>
                                        </a>
                                    </li>
                                    <li class="nav-logout">
                                        
                                        <a href="">
                                            <span class="lnr">
                                                <form action="{% url 'home:logout' %}" method="POST">
                                                    {% csrf_token %}
                                                    <button class="btn btn-danger btn-logout">
                                                        LogOut
                                                    </button>
                                                </form>
                                                
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </div><!--/.attr-nav-->
                            <!-- End Atribute Navigation -->
    
                            <!-- Start Header Navigation -->
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                                    <i class="fa fa-bars"></i>
                                </button>
                                <a class="navbar-brand" href="index.html">sine<span>mkt</span>.</a>
    
                            </div><!--/.navbar-header-->
                            <!-- End Header Navigation -->
    
                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div class="collapse navbar-collapse menu-ui-design" id="navbar-menu">
                                <ul class="nav navbar-nav navbar-center" data-in="fadeInDown" data-out="fadeOutUp">
                                    <li class=" active"><a href="{% url 'home:home' %}">home</a></li>
                                    <li class=""><a href="#feature">features</a></li>
                                    <li class=""><a href="">blog</a></li>
                                    <li class=""><a href="#newsletter">contact</a></li>
                                    <li class=" "><a href="#new-arrivals">new arrival</a></li>
                                    
                                </ul><!--/.nav -->
                            </div><!-- /.navbar-collapse -->
                        </div><!--/.container-->
                        <div class="cart">
                            {% with total_items=cart|length %}
                                {% if total_items == 0 %}
                                    Cart is empty
                                {% else %}
                                    Your Cart: {{total_items}},${{cart.get_total_price}}
                                {% endif %}
                            {% endwith %}
                        </div>
                    </nav><!--/nav-->
                    <!-- End Navigation -->
                </div><!--/.header-area-->
                <div class="clearfix"></div>
    
            </div>
            {% block header %}  {% endblock header %}
           
        </header>
        <div class="container">
            <div class="content_extends">
                {% block content %} {% endblock content %}
            </div>
            
        </div>
        
        {% block script %}  {% endblock script %} 
        <script src="/media/assets/js/jquery.js"></script>
		
		<!--modernizr.min.js-->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
		
		<!--bootstrap.min.js-->
		<script src="/media/assets/js/bootstrap.min.js"></script>
		
		<!-- bootsnav js -->
		<script src="/media/assets/js/bootsnav.js"></script>

		<!--owl.carousel.js-->
		<script src="/media/assets/js/owl.carousel.min.js"></script>


		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
		
		
		<!--Custom JS-->
		<script src="/media/assets/js/custom.js"></script>
    </body>
    
    
</html>

build_shop/templates/home/home.html
{% extends "home/base.html" %}
{% block content %}
    <div> chao mung :{{request.user.username }}</div>            
{% endblock content %}

build_shop/templates/home/login-register.html
{% extends 'authentication/base.html' %}
{% load static %}


{% block head %} 
    <meta charset="utf-8">
    <title>Login</title>
    <link href='http://fonts.googleapis.com/css?family=Ropa+Sans' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'authentication/login.css' %}">
{% endblock head %}



{% block content %}
    <div id="login-form">

        <input type="radio"  id="login" name="switch" class="hide">
        <input type="radio" checked id="signup" name="switch" class="hide">

        <div>
            <ul class="form-header">
                <li><label for="login"><i class="fa fa-lock"></i> LOGIN<label for="login"></li>
                <li><label for="signup"><i class="fa fa-credit-card"></i> REGISTER</label></li>
            </ul>
        </div>

        <div class="section-out">
            <section class="login-section">
                <div class="login">
                    <form id="form-login"   method="POST">
                        {% csrf_token %}
                        <ul class="ul-list">
                           {% for field in login_form %}
                                <li class='box-{{field.name}}'>
                                    <span>{{field.name}}</span>
                                    <div>
                                        {{field}}
                                        <div>
                                            <span class="mess_error " id="login-error-{{field.name}}" ></span>
                                        </div>
                                    </div>
                                </li>

                            {% endfor %}
                           <li ><span class="mess_error" id="login-error-mess_account">
                               
                           </span></li>
                            <input type="hidden" name="form-type" value="login_form">
                            <li><input id="input-login" type="submit" value="SIGN IN" class="btn" name="submit-login"></li>
                            
                        </ul>
                    </form>
                </div>

                <div class="social-login">Or sign in with &nbsp;
                    <a href="" class="fb"><i class="fa fa-facebook"></i></a>
                    <a href="" class="tw"><i class="fa fa-twitter"></i></a>
                    <a href="" class="gp"><i class="fa fa-google-plus"></i></a>
                    <a href="" class="in"><i class="fa fa-linkedin"></i></a>
                </div>
            </section>

            <section class="signup-section">
                <div class="login">
                    <form action="" method="post">
                        <ul class="ul-list">
                            {% csrf_token %}
                            <li>{{register_form.username}}
                                
                            </li>
                            <li>
                                {{register_form.password_1}}
                              
                            </li>
                            <li>
                                {{register_form.password_2}}
                                {{register_form.password_2.errors}}
                            
                            </li>
                            <input type="hidden" name="form-type" value="register_form">
                            <input type="submit" value="submit">
                        </ul>

                    </form>
                </div>

                <div class="social-login">Or sign up with &nbsp;
                    <a href="" class="fb"><i class="fa fa-facebook"></i></a>
                    <a href="" class="tw"><i class="fa fa-twitter"></i></a>
                    <a href="" class="gp"><i class="fa fa-google-plus"></i></a>
                    <a href="" class="in"><i class="fa fa-linkedin"></i></a>
                </div>
            </section>
        </div>

    </div>
    <div id="cccc">
        a
    </div>
{% endblock content %}

  

{% block script %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      

      <script>

            
          $('#form-login').submit(function(e){
                e.preventDefault()
                $('.mess_error').text('')
                var serializedData=$(this).serialize()
                $.ajax({
                    type:'POST',
                    url:" {% url 'home:login-register' %}",
                    data:serializedData,
                    success: function(response){
                        if(response['valid']==false){
                            alert(response['error_dict'])
                                errors_dict=JSON.parse(response['error_dict'])
                                
                                for(var key in errors_dict ){
                                    mess_name='login-error-'+key
                                    for(var i in errors_dict[key]){
                                        $('#'+mess_name).append(errors_dict[key][i])
                                    }
                                }
                        }   
                        else{
                            if(response['is_admin']==false){
                                window.location.replace("{% url 'home:home' %}");
                            }
                            else{
                                window.location.replace("{% url 'management:dashboard' %}");
                            }
                        }
                       
                    },
                    error: function(response){
                        alert("loi!")
                    }
                })
       
          })


          
          
      </script>
{% endblock script %} 






    