build_shop/User/urls.py
from django.urls import path,include
from .import views
app_name="user"
urlpatterns = [
    path('addDelivery/',views.CreateDelivery.as_view(),name="add_delivery"),
]

build_shop/build_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('user/',include('User.urls')),
    path('management/',include('management_owner.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

build_shop/orders/urls.py
from django.urls import path,include
from .import views
app_name="orders"
urlpatterns = [
    path('detail/<slug:slug>/',views.Order_Detail.as_view(),name="order_detail"),
    path('',views.Order_Detail.as_view(),name="order_detail_all"),
    path('create_order/',views.CreateOrder.as_view(),name="create_order"),
    path('validateId',views.validateId,name="validateId"),
    path('cc',views.index),
]

build_shop/orders/models.py
from django.db import models
from User.models import Customer,DeliveryInfor
from shop.models import Product
# Create your models here.

class Order(models.Model):
    id=models.CharField(primary_key=True, max_length=12)
    name=models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    slug=models.SlugField(unique=True)
    products=models.ManyToManyField(Product,related_name='products',through='OrderItem')
    delivery_infor=models.ForeignKey(DeliveryInfor,on_delete=models.CASCADE)
    
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return 'Order-{}-{}'.format(self.name,self.id)
    
    def get_total_cost(self):
        items=OrderItem.objects.filter(order=self)
        return sum([item.price*item.quantity for item in items])
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    

    

build_shop/orders/forms.py
from django import forms
from .models import Order
from shop.models import Product
from User.models import DeliveryInfor

# PRODUCT_LIST=(
    
# )

class OrderCreateForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields=['id','name','paid','slug','delivery_infor']
        
    def __init__(self,request,*arg,**kwargs):
        super().__init__(*arg,**kwargs)
        
        for field in self.fields:
            if field not in ['delivery_infor','products','paid']:
                self.fields[field].widget.attrs.update({'class':'form-control'})
            
            if field =="delivery_infor":
                self.fields[field]=forms.ModelChoiceField(queryset=request.user.customer.delivery_infor.all())
            
            
    
                
        
    
        
        
        
    
        

build_shop/orders/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse,JsonResponse
from User.models import *
from User.models import Customer
from .models import OrderItem
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from cart.models import Cart
from .forms import OrderCreateForm
from .models import Order,OrderItem
from django.views import View
from django.utils import timezone
from django.db.models import Count ,F,Sum
from shop.recomender import *
from .tasks import order_created
class Order_Detail(TemplateView):
    template_name='orders/orders_detail.html'
    
    def get(self, request, slug=None):
        user=self.request.user
        orders=Order.objects.filter(delivery_infor__customer__user=user)
        if slug is not None:
            order=Order.objects.get(slug=slug)
        else:
            order=Order.objects.first()
        order_items=OrderItem.objects.filter(order=order).annotate(total_price=F('price')*F('quantity'))
        total_cost_order=order_items.aggregate(Sum('total_price'))['total_price__sum']
        # print(total_cost_order['total_price__sum'])
        return super().get(request,orders=orders,order_items=order_items,total_cost_order=total_cost_order)
        
    
class CreateOrder(View):
    def get(self ,request):
        form=OrderCreateForm(request=request)
        return render(request,'orders/create_order.html',{'form':form})
    
    def post(self,request):
            cart = Cart(request)
            form=OrderCreateForm(request,request.POST)
            re=Recommender()
            list_product=[]
            
            if form.is_valid():
                try:
                    instance=Order.objects.get(id=request.POST['id'])
                except:
                    instance=None
                if instance is  None:
                    # print(form.cleaned_data)
                    order=form.save()
                    for item in cart:
                        OrderItem.objects.create(order=order,
                                                product=item['product'],
                                                price=item['price'],
                                                quantity=item['quantity'])
                        list_product.append(item['product'])
                    # get infor of product to recommend next product
                    re.products_bought(list_product) 
                    
                    cart.clear()
            
                    # task=order_created.delay('1')
                    # print(f"id={task.id}, state={task.state}, status={task.status}") 
                    return redirect('orders:order_detail_all')
            return HttpResponse("fail!")
    

def validateId(request):
        if request.is_ajax:
            try:
                instance=Order.objects.get(id=request.POST['id'])
            except:
                instance=None
        if instance is None:
            check=True
        else:
            check=False
        return JsonResponse({'valid':check})
# def checkDuplicateId(request):
    
        
        
        
from time import sleep

def index(request):
    sleep(5)
    print("hih")
    return render(request,'cc.html')

build_shop/templates/orders/create_order.html
{% extends "home/base.html" %}

{% block title %}
    <title>
        Create-Order
    </title>
{% endblock title %} 
{% block style %}
    <style>
        .main{
          margin-top:15%;
        }
    </style>
{% endblock style %}
{% block content %}
<div class="main">
  <form id="create-order-form" action="." method="post">
    <div class="csrf_token">
      {% csrf_token %}
    </div>
    {% for field in form %}
    <div class="form-group">
      {% if field in form.visible_fields %}
        <label for="">{{field.name}}</label>
      {% endif %}
      {{field}}


    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
   
</div>
{% endblock content %}

{% block script %}
  <script>
    $("#id_id").focusout(function(e){
      e.preventDefault();
      var id=$(this).val()
      var csrf_token=document.querySelector('#create-order-form >.csrf_token input').value
      var data="csrfmiddlewaretoken="+csrf_token+"&id="+id 

      $.ajax({
        type:'POST',
        url:"{% url 'orders:validateId' %}",
        data:data,
        success:function(reponse){
          if(reponse['valid']==false){
            alert("Have Existed Id")
            $("#id_id").val("concac");            
          }
        }

      })
    })
  </script>    
{% endblock script %}

build_shop/templates/orders/orders_detail.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
    <title>
        Order Detail
    </title>
{% endblock title %}
{% block style %}
    <style>
        .main{
            margin-top: 15%;
        }
    
    </style>
{% endblock style %}
    
{% block content  %}  
    <div class='main'>
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    {% for order in orders %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{% url 'orders:order_detail' order.slug %}">{{order.name}}</a>
                        <span class="badge badge-primary badge-pill">${{ order.get_total_cost}}</span>
                    </li>
                    {% endfor %}
                  </ul>
            </div>
            <div class="col-md-8">
                <table class="table">
                    <thead class="thead-dark">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Price</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for item in order_items %}
                      <tr>
                        {% with x=forloop.counter%}
                        <th scope="row">{{x}}</th>
                        {% endwith %}
                        <td>{{item.product.name}}</td>
                        <td>${{item.product.price}}</td>
                        <td>{{item.quantity}}</td>
                        <td>{{item.total_price}}</td>
                      </tr>
                    {% endfor %}
                    <tr>
                        <th scope="row"></th>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>${{total_cost_order}}</td>
                      </tr>
                    </tbody>
                  </table>
                  
                
            </div>
        </div>
    </div>
{% endblock content %}  