build_shop/User/urls.py
from django.urls import path,include
from .import views
app_name="user"
urlpatterns = [
    path('addDelivery/',views.CreateDelivery.as_view(),name="add_delivery"),
]

build_shop/build_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('user/',include('User.urls')),
    path('management/',include('management_owner.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

build_shop/cart/urls.py
from django.urls import path
from .import views

app_name='cart'
urlpatterns = [
    path('',views.DetailCart.as_view(), name="detail_cart"),
    path('delete/<str:product_id>/',views.deleteProductCart,name="delete_product_cart"),
    path('product_detail/<slug:slug>/',views.AddProductCart.as_view(),name='add_product_cart'),
    path('post_comment/>',views.post_Comment,name='post_comment'),
    path('test/',views.test.as_view()),
]

build_shop/orders/urls.py
from django.urls import path,include
from .import views
app_name="orders"
urlpatterns = [
    path('detail/<slug:slug>/',views.Order_Detail.as_view(),name="order_detail"),
    path('',views.Order_Detail.as_view(),name="order_detail_all"),
    path('create_order/',views.CreateOrder.as_view(),name="create_order"),
    path('validateId',views.validateId,name="validateId"),
    path('cc',views.index),
]

build_shop/cart/models.py
from django.db import models
from django.conf import settings
from decimal import Decimal
from shop.models import Product
# Create your models here.
class Cart(object):
    
    def __init__(self,request):
        self.session=request.session
        cart=self.session.get(settings.CART_SESSION_ID)
        if not cart:
            cart=self.session[settings.CART_SESSION_ID]={}
        self.cart=cart
    
    def add(self,product,discount_percent=0,quantity=1,update=False):
        
        product_id=product.Product_id
        price=(product.price)*(100-discount_percent)/100
        if product_id  not in self.cart:
            
            self.cart[str(product_id)]={'quantity':quantity,'price':str(price)}
        else:
            if not update:
                self.cart[str(product_id)]['quantity']+=quantity
            else:
                
                self.cart[str(product_id)]['quantity']=quantity
                
        self.save()
    
    def save(self):
        # update the session cart
        self.session[settings.CART_SESSION_ID] = self.cart
    
    def remove(self,product_id):
        del self.cart[str(product_id)]
        
    
    def get_total_price(self):
        total_price=0
        for product_infor in self.cart.values():
            total_price+=(product_infor['quantity']*Decimal(product_infor['price']))
        return total_price
    
    def __iter__(self):
        product_ids=self.cart.keys()
        products=Product.objects.filter(Product_id__in=product_ids)
        for product in products:
            self.cart[str(product.Product_id)]['product']=product
            
        for item in self.cart.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item
    
    def __len__(self):
        return len(self.cart.keys())
    
    def clear(self):
        del self.session[settings.CART_SESSION_ID]
        
                 
        

build_shop/cart/forms.py
from wsgiref.validate import validator
from django import forms
from django.core.exceptions import ValidationError
PRODUCT_QUANTITY_CHOICES=[ (i,str(i) )for i in range(1,21)]
def check_quantity(value):
    if int(value)<1:
        raise ValidationError('<0')
    
class CartAddProduct(forms.Form):
    
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,validators=[check_quantity])
    update = forms.BooleanField(required=False,
                                initial=False,
                                )
    code=forms.CharField(required=False)

class PostCommentForm(forms.Form):
    body=forms.CharField(widget=forms.TextInput,required=True)
    # product=forms.HiddenInput()
    # def __init__(self,request,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
        # self.fields['product'].widget.attrs.update({'class':'form-control',})
        

build_shop/cart/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render,get_object_or_404
from .models import Cart
from .forms import CartAddProduct , PostCommentForm
from shop.models import Product
from django.views.generic import TemplateView 
from django.views.generic.edit import FormView
from django.views import View
from coupons.models import Coupon
from django.core.exceptions import ValidationError
from shop.recomender import Recommender
from actions.models import *
from django.contrib.contenttypes.models import ContentType
from django.views.decorators.http import require_POST

# Create your views here.

class DetailCart(TemplateView):
    template_name='cart/detail_cart.html'
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['cart']=Cart(self.request)
        return context


class AddProductCart(TemplateView):
    template_name='cart/add_product_cart.html'
    cart_add_form = CartAddProduct()
    post_comment_form=PostCommentForm()
    context={}
    def get(self,request,slug=None):
        try:
            product=Product.objects.get(slug=slug)
        except:
            product=None
        #call get_context_data
        context_data=self.get_context_data()
        print("context:",context_data)
        
        #form 
        context_data['cart_add_form']=self.cart_add_form    
        context_data['post_comment_form']=self.post_comment_form
        
        #recommender system
        re=Recommender()
        flag_ids=re.suggest_products_for(product.Product_id)
        context_data['product']=product
        
        if flag_ids!=None:
            recommended_products=Product.objects.filter(Product_id__in=flag_ids)
            context_data['recommended_products']=recommended_products
            
                  
        
        #comments
        comment_type=ContentType.objects.get(app_label='actions',model='Comment') 
        comments=Action.objects.filter(product=product,content_type=comment_type) 
        context_data['comments']=comments   
        
        #update context
        self.context.update(context_data)              
        return self.render_to_response(self.context)
    
    
    def post(self,request,slug):
        
        if request.POST.get('form-type')=='card-add-form':
            form=CartAddProduct(request.POST)
            if form.is_valid():    
                cd=form.cleaned_data
                try:
                    coupon=Coupon.objects.get(code=cd['code'])
                except:
                    coupon=None
                return addProductCart(self.request,self.context['product'],coupon,cd)
        return HttpResponse("fail!") 
        
@require_POST
def post_Comment(request):
    if request.POST.get('form-type')=='post-comment-form' and request.is_ajax():
        from django.utils.timezone import now
        form=PostCommentForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            
            #create Comment object
            import random
            while True:
                id_comment_instance=str(random.randint(0,10^20))
                
                if id_comment_instance not in Comment.objects.values_list('id',flat=True):
                    break
            Comment.objects.create(
                    id=id_comment_instance,
                    body=cd['body']
            )
            #create Action
            
            action_instance=Action.objects.create(
                user=request.user,
                product=Product.objects.get(Product_id=request.POST.get('product_id')),
                content_type=ContentType.objects.get(
                    app_label='actions',
                    model='Comment'),
                object_id=id_comment_instance
            )
            print("::::::::::",action_instance.create_at)
            return JsonResponse({'valid':True,'time':action_instance.create_at})
        else:
            return JsonResponse({'valid':False})
            


        

    
def addProductCart(request,product,coupon,cd):
    cart=Cart(request)
    if coupon is not None:
        discount=coupon.discount
    else:
        discount=0
    cart.add(product,discount,cd['quantity'],cd['update'])
    cart.save()
    return redirect('cart:detail_cart')

def deleteProductCart(request,product_id):
    cart=Cart(request)
    cart.remove(product_id)
    cart.save()
    return JsonResponse({'valid':True,'total_price':cart.get_total_price()})

# def checkoutCart(request):

#     return HttpResponse("check out") 

class test(TemplateView):
    template_name='cc.html'
    def get(self,request,quan):
        try:
            print("::::::::::::::::",quan)
            
        except:
            pass
        return super().get(request)
    def post(self,request):
        return HttpResponse("oke")

build_shop/templates/cart/add_product_cart.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}
    <title>
        detail-{{ product.name }}
    </title>
{% endblock title %}
{% block link %}
    <link rel="stylesheet" href="{% static 'products/comments.css' %}">
{% endblock link %}
{% block style %}
    <style>
        .form-add-cart{
            margin-top:10%;
            background-color: aqua;
        }
        .form-add-cart{
            width:500px;
            text-align:center
        }
        .container >.form-add-cart{
            margin: 15%;
        }
        .img-box >img{
            width:100%;
            height:100%;
        }
        .content_extends{
            margin:20% 20%;
        }
    
    </style>
{% endblock style %}
{% block content  %}  

    <div class="submit-product">
        <form action="."  method="POST">
            <div class="row">
                <div class="col-md-6 img-box" >
                    <img src="{{ product.image.url }}" alt="">
                </div>
                <div class="col-md-6 form-box">
                    {% csrf_token %}
                    {{cart_add_form.as_p}}
                    
                </div>
                <div class="meassage">
                    {{product}}
                </div>
            </div>
            <input type="hidden" name="form-type" value="card-add-form">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="recomender">
        <div class="row">
            {% if recommended_products %}
                {% for product in recommended_products %}
                <div class="col-lg-4 col-md-6"><img src="{{ product.image.url }}" alt="">
                        <a href="{{ product.get_absolute_url }}"> {{product.name}}</a>
                </div>
                {% endfor %}
            {% endif %}
            
        </div>
    </div>
    <div class="container mt-5">
        <div class="d-flex justify-content-center row">
            <div class="col-md-6">
                <div id='box-comment' class="p-3 bg-white rounded">
                    <h6>Reviews[8]</h6>
                    {% for comment_object in comments %}
                    <div class="review mt-4">
                        <div class="d-flex flex-row comment-user"><img class="rounded" src="https://i.imgur.com/xxJl1D7.jpg" width="40">
                            <div class="ml-2">
                                <div class="d-flex flex-row align-items-center"><span class="name font-weight-bold">{{comment_object.user.name}}</span><span class="dot"></span><span class="date">{{comment_object.create_at}}</span></div>
                                <div class="rating"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
                            </div>
                        </div>
                        <div class="mt-2">
                            <p class="comment-text">{{comment_object.content_object.body}}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <form id="post-comment-form">
                    {% csrf_token %}
                    {{post_comment_form}}
                    <input type="hidden" name="product_id" value="{{product.Product_id}}">
                    <input type="hidden" name="form-type" value="post-comment-form">
                    <button id="btn-post-comment" type="submit" class="btn btn-primary">Submit</button>
                </form>   
                
            </div>
        </div>
    </div>

    
  
{% endblock content %}  

{% block script %}
    <script>
        $('#post-comment-form').submit(function(e){
            e.preventDefault()
            var data=$(this).serialize()
    
            $.ajax({
                type:'POST',
                url:"{% url 'cart:post_comment' %}",
                data:data,
                success(reponse){
                    var time=reponse['time'] 
                    
                    if (reponse['valid']==true){
                        $("#box-comment").append(
                            "<div class='review mt-4'>"+
                                "<div class='d-flex flex-row comment-user'><img class='rounded' src='https://i.imgur.com/xxJl1D7.jpg' width='40'>"+
                                    "<div class='ml-2'>"+
                                        "<div class='d-flex flex-row align-items-center'><span class='name font-weight-bold'>"+'{{user.name}}'+"</span><span class='dot'></span><span class='date'>"+time
                                            +"</span></div>"+
                                        "<div class='rating'><i class='fa fa-star'></i><i class='fa fa-star'></i><i class='fa fa-star'></i><i class='fa fa-star'></i></div>"+
                                    "</div>"+
                                "</div>"+
                                "<div class='mt-2'>"+
                                    "<p class='comment-text'>"+$('#id_body').val()+"</p>"+
                                "</div>"+
                            "</div>"
                        )
                        $('#id_body').val("")
                    }
                    else{
                        alert('Fail!')
                    }
                            

                        

                    
                }
            })
        })
    </script>
{% endblock script %}

build_shop/templates/cart/detail_cart.html
{% extends "home/base.html" %}

{% block title %}
    <title>
        Detail-Cart
    </title>
{% endblock title %} 

{% block style %}
    <style>        
        .style-table{
          padding:15%;
        }
        
        
        
    
    </style>
{% endblock style %}



{% block content %}
<form id ="form-cart-table" action="{% url 'orders:create_order' %}" method="GET">
  <div class="csrf_token">
        {% csrf_token %} 
  </div>
  <div class="style-table">
    
      <table class="table cart-detail-table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody id="body-cart-table">
          {% for item in cart %}
            <tr id="row-product_id-{{item.product.Product_id}}">
              <th scope="row">{{forloop.counter}}</th>
              <td>{{item.product.name}}</td>
              <td>{{item.quantity}}</td>
              <td>${{item.price}}</td>
              <td>{{item.total_price}}</td>
              <td><button type="button" class="btn btn-danger delete-btn" name="btn-delete-{{item.product.Product_id}}">X</button></td>
            </tr>
          {% endfor %}
        
          <tr>
            <th ></th>
            <th ></th>
            <th ></th>
            <th ></th>
            <th id="total-price-box" name="ahi">${{cart.get_total_price}}</th>
            <th><input type="submit" class="form-control" name="checkout" value="Check Out"></th>
          </tr>
        </tbody>
      </table>
    
  </div>
</form>
{% endblock content %}

{% block script %}
    <script>
      $(".delete-btn").click(function(){

        var index=$(this).attr('name').lastIndexOf('-');
        var product_id=$(this).attr('name').slice(index+1);
        var url='/cart/delete/'+product_id+'/'
        var csrf_token=document.querySelector('#form-cart-table .csrf_token >input').value
        data="csrfmiddlewaretoken="+csrf_token
        $.ajax({
          type:'POST',
          url:url,
          data:data,
          success: function(response){
              if(response['valid']==true){
                let tr_delete=document.getElementById('row-product_id-'+product_id)
                document.getElementById('body-cart-table').removeChild(tr_delete)
                document.getElementById('total-price-box').innerHTML="$"+response['total_price']              
              }
          }
        })
      })
        
         
    </script>
{% endblock script %}